Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.provision "shell" do |s|
    ssh_pub_keys = File.read("./.ssh_public_keys")
    s.inline = <<-SHELL
    echo "#{ssh_pub_keys}" >> /home/vagrant/.ssh/authorized_keys
    #echo {ssh_pub_keys} >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "db" do |node|
    node.vm.hostname = "db"
    node.vm.network "private_network", ip: "172.16.16.100"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "3"
    end

    node.vm.disk :disk, name: "zfs", size: "32GB", primary: false
  end

  config.vm.define "worker" do |node|
    node.vm.hostname = "worker"
    node.vm.network "private_network", ip: "172.16.16.110"
  end

  config.vm.define "monitor" do |node|
    node.vm.hostname = "monitor"
    node.vm.network "private_network", ip: "172.16.16.120"
  end

end
