services:
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: postgresql://${db_user}:${db_password}@${host}:5432
    network_mode: host