---
- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: change default name
  command:
    cmd: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{PG_PASSWORD}}';"