services:
  ingress:
    image: nginx:1.25-bookworm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/ssl/server-key.pem:/etc/ssl/nginx/key.pem:ro
      - ./conf/nginx/ssl/server.pem:/etc/ssl/nginx/cert.pem:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
    restart: always
    networks:
      - monitoring
      - back_channel

networks:
  monitoring:
    name: monitoring-bridge
    driver: bridge
  back_channel:
    name: back_channel-bridge
    driver: bridge